name: .NET CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  

  release:
    #needs: build-and-test
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Archive Application
      run: |
        dir
        # Create a directory for the release package
        mkdir release
        # Copy your application files to the release directory (adjust the path accordingly)
        cp -r . release
        # Compress the application into a zip file
        7z a -tzip release.zip ./release/*

    - name: Upload to GitHub Releases
      id: upload-release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
