name: .NET CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

  release:
    needs: build-and-test
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Archive Application
      run: |
        # Create a directory for the release package
        mkdir release
        # Copy your application files to the release directory (adjust the path accordingly)
        cp -r Expect.ModManager.Test\bin\Debug\net7.0-windows release
        # Compress the application into a zip file
        7z a -tzip release.zip ./release/*

    - name: Upload to GitHub Releases
      id: upload-release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
